[package]
name = "todos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redux-rs = { git = "https://github.com/jeroenvervaeke/redux-rs.git", rev = "1774ba7e7dc624be09607c63b68ef11c67f3460a" }